# Form implementation generated from reading ui file 'ui_selectreport.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SelectReport(object):
    def setupUi(self, SelectReport):
        SelectReport.setObjectName("SelectReport")
        SelectReport.resize(400, 300)

        self.retranslateUi(SelectReport)
        QtCore.QMetaObject.connectSlotsByName(SelectReport)

    def retranslateUi(self, SelectReport):
        _translate = QtCore.QCoreApplication.translate
        SelectReport.setWindowTitle(_translate("SelectReport", "报告选项选择"))
